UPD - .travis.sh
Add missing java 1.8 to install rule from travis file.

> bazel: Java 1.8 is required to install this formula.
> JavaRequirement unsatisfied!
> You can install with Homebrew Cask:
> `brew cask install homebrew/cask-versions/java8`
> You can download from:
> https://www.oracle.com/technetwork/java/javase/downloads/index.html
> Error: An unsatisfied requirement failed this build.

Signed-off-by: Maxime Killinger <max.killinger@outlook.fr>

modifié :         .travis.sh